services:
  - type: web
    name: opensource-testing
    env: java
    plan: free
    branch: main
    repo: https://github.com/ranuanand/OpenSourceTesting
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/OpenSourceTesting-0.0.1-SNAPSHOT.jar
